language: bash

install:
    - source ./.travis/setup.sh

script:
    - git push hdmi2usb@build.hdmi2usb.tv:build "$BRANCH_NAME"

notifications:
    email:
        - hdmi2usb-spam@googlegroups.com
    irc:
        channels:
            - "chat.freenode.net#hdmi2usb"
            - "chat.freenode.net#timvideos"
        template:
            - "[%{repository_slug}/%{branch}#%{build_number}] (%{commit}): %{message} (%{build_url})"
    
